import type { Metadata } from "next";
import "./globals.css";
import { Galmuri9, Pretendard } from "./fonts";

export const metadata: Metadata = {
  title: "Stuv",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Pretendard.variable} ${Galmuri9.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
