name: deploy at EC2

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
      
  # Actions 탭에서 수동으로 워크플로우를 실행할 수 있도록 구성
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 인스턴스 pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/WEB2_3_Wooamo_FE
            git pull origin main
            pm2 kill
            pnpm install
            pnpm build
            pm2 start "sudo pnpm start"
